Clean up logging. Do not invoke etckeeper when there are no changes to /etc.

diff --git a/provisioning/bootstrap.d/10-apt-get-update b/provisioning/bootstrap.d/10-apt-get-update
--- a/provisioning/bootstrap.d/10-apt-get-update
+++ b/provisioning/bootstrap.d/10-apt-get-update
@@ -1,4 +1,3 @@
-msg="BCE: Updating apt cache..."
-echo $msg
+echo "BCE: Updating apt cache..."
 $APT_GET update > /dev/null && \
-echo DONE: $msg || echo FAIL: $msg
+echo "  DONE" || echo "  FAIL"
diff --git a/provisioning/bootstrap.d/20-guest-additions b/provisioning/bootstrap.d/20-guest-additions
--- a/provisioning/bootstrap.d/20-guest-additions
+++ b/provisioning/bootstrap.d/20-guest-additions
@@ -2,7 +2,7 @@ echo "BCE: Installing build utilities..."
 # This is more robust - redundancy is not a problem!
 $APT_GET install build-essential dkms xserver-xorg dmidecode curl \
     software-properties-common && \
-echo DONE || echo FAIL
+echo "  DONE" || echo "  FAIL"
 
 # An alternative method would be to manually share the directory on the host
 # which actually contains VBoxGuestAdditions.iso. On a Mac that is
@@ -23,6 +23,6 @@ if [ "${PACKER_BUILDER_TYPE}" == "virtualbox-iso" ]; then
     /mnt/VBoxLinuxAdditions.run -- --force
     # XXX We break logical chaining here, because it's never working!
     eject /mnt && \
-    ( echo DONE ; etckeeper commit "$msg" ) || echo FAIL
-    #echo DONE: $msg || echo "FAIL (but not really?):" $msg
+    ( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
+    #echo "  DONE" || echo "FAIL (but not really?):" $msg
 fi
diff --git a/provisioning/bootstrap.d/40-ubuntu-packages b/provisioning/bootstrap.d/40-ubuntu-packages
--- a/provisioning/bootstrap.d/40-ubuntu-packages
+++ b/provisioning/bootstrap.d/40-ubuntu-packages
@@ -1,5 +1,4 @@
-msg="BCE: Installing Ubuntu packages..."
-echo "$msg"
+echo "BCE: Installing Ubuntu packages..."
 # This ensures we get security updates, etc.
 # Note that this is ALSO done currently by the debian-installer step...
 $APT_GET dist-upgrade && \
@@ -11,4 +10,4 @@ $APT_GET install --no-install-recommends \
 $APT_GET install $(grep '^[^#]' /tmp/packages/ubuntu-packages.txt) && \
 # help avoid running out of disk space
 $APT_GET clean && \
-echo DONE: $msg  || echo FAIL: $msg
+echo "  DONE"  || echo "  FAIL"
diff --git a/provisioning/bootstrap.d/50-oski b/provisioning/bootstrap.d/50-oski
--- a/provisioning/bootstrap.d/50-oski
+++ b/provisioning/bootstrap.d/50-oski
@@ -10,12 +10,9 @@ else
 fi && \
 # Enable our user to login without a password
 adduser ${BCE_USER} nopasswdlogin && \
-( echo DONE ; etckeeper commit "$msg" ) || echo FAIL
+( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
 
-# Create a convenient place on the desktop for people to mount
-# their Shared Directories.
-msg="BCE: Configure ${BCE_USER} (and other) desktops"
-echo "$msg"
+echo "BCE: Configure ${BCE_USER} (and other) desktops"
 if [ "${PACKER_BUILDER_TYPE}" == "amazon-ebs" ]; then
     # We are initially copying files to the (pre-existing) ubuntu user
     cp -r /home/ubuntu/.config /home/${BCE_USER}/.config && \
@@ -25,17 +22,17 @@ if [ "${PACKER_BUILDER_TYPE}" == "amazon-ebs" ]; then
 else
     chmod 755 /home/${BCE_USER}/setup_ipython_notebook.sh
 fi && \
+echo "  DONE" || echo "  FAIL"
 
-# XXX - This may also be appropriate for VMware
-# This provides obvious access to shared folders in VBox
+# Create a convenient place on the desktop for people to mount and access
+# their shared directories. This may also be appropriate for VMware.
 if [ "${PACKER_BUILDER_TYPE}" == "virtualbox-iso" ]; then
-  sudo -u ${BCE_USER} mkdir /home/${BCE_USER}/Desktop && \
-  sudo -u ${BCE_USER} ln -s /media /home/${BCE_USER}/Desktop/Shared
-fi && \
-echo DONE || echo FAIL
+	echo "BCE: Configure shared directory for ${PACKER_BUILDER_TYPE}"
+	sudo -u ${BCE_USER} mkdir /home/${BCE_USER}/Desktop && \
+	sudo -u ${BCE_USER} ln -s /media /home/${BCE_USER}/Desktop/Shared && \
+	echo "  DONE" || echo "  FAIL"
 
-# Automatically login at boot
-if [ "${PACKER_BUILDER_TYPE}" == "virtualbox-iso" ]; then
+	# Automatically login at boot
 	msg="BCE: Automatically login ${BCE_USER} at boot"
 	( cat <<EOF > /etc/lightdm/lightdm.conf
 [SeatDefaults]
@@ -43,7 +40,7 @@ autologin-user=${BCE_USER}
 autologin-user-timeout=0
 EOF
 	) && \
-	( echo DONE ; etckeeper commit "$msg" ) || echo FAIL
+	( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
 fi
 
 ## For if/when we don't want a display manager
diff --git a/provisioning/bootstrap.d/60-google-chrome b/provisioning/bootstrap.d/60-google-chrome
--- a/provisioning/bootstrap.d/60-google-chrome
+++ b/provisioning/bootstrap.d/60-google-chrome
@@ -7,4 +7,4 @@ curl -L https://dl-ssl.google.com/linux/linux_signing_key.pub | \
     apt-key add - && \
 $APT_GET update > /dev/null && \
 $APT_GET install google-chrome-stable && \
-echo DONE: $msg  || echo FAIL: $msg
+echo "  DONE"  || echo "  FAIL"
diff --git a/provisioning/bootstrap.d/70-r b/provisioning/bootstrap.d/70-r
--- a/provisioning/bootstrap.d/70-r
+++ b/provisioning/bootstrap.d/70-r
@@ -2,12 +2,11 @@ msg="BCE: Installing add-on R packages..."
 echo "$msg"
 Rscript -e "pkgs <- scan('/tmp/packages/R-packages.txt', what = 'character'); \
 install.packages(pkgs, repos = 'http://cran.cnr.berkeley.edu')" && \
-echo DONE: $msg || echo FAIL: $msg
+echo "  DONE" || echo "  FAIL"
 
-msg="BCE: Adding R to Development menu..."
-echo "$msg"
+echo "BCE: Adding R to Development menu..."
 sed -i \
 	-e '/^Categories=/s/Graphics;//' \
 	-e '/^Categories=/s/=/=Development;/' \
 	/usr/share/applications/R.desktop && \
-echo DONE: $msg || echo FAIL: $msg
+echo "  DONE" || echo "  FAIL"
diff --git a/provisioning/bootstrap.d/75-rstudio b/provisioning/bootstrap.d/75-rstudio
--- a/provisioning/bootstrap.d/75-rstudio
+++ b/provisioning/bootstrap.d/75-rstudio
@@ -1,7 +1,6 @@
-# R, RStudio
-msg="BCE: Installing RStudio..."
-echo "$msg"
+# RStudio
+echo "BCE: Installing RStudio..."
 RSTUDIO_URL=http://download1.rstudio.org/rstudio-0.98.1091-amd64.deb
 curl -L -O ${RSTUDIO_URL} && \
 dpkg -i $(basename ${RSTUDIO_URL}) && \
-( echo DONE ; etckeeper commit "$msg" ) || echo FAIL
+( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
diff --git a/provisioning/bootstrap.d/80-python b/provisioning/bootstrap.d/80-python
--- a/provisioning/bootstrap.d/80-python
+++ b/provisioning/bootstrap.d/80-python
@@ -1,5 +1,4 @@
-msg="BCE: Installing Python modules..."
-echo "$msg"
+echo "BCE: Installing Python modules..."
 # We install pip directly from pypa to avoid conflicts with requests
 curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && \
 python /tmp/get-pip.py && \
@@ -9,15 +8,13 @@ for p in $(egrep -v '^$|^#' /tmp/packages/python-requirements.txt); do
 	echo $cmd
 	$cmd
 done && \
-echo DONE: $msg || echo FAIL: $msg
+echo "  DONE" || echo "  FAIL"
 # This isn't as reliable as doing one at a time
 #pip install --upgrade -r /tmp/packages/python-requirements.txt && \
 
-msg="BCE: Creating python panel menu launchers..."
-echo "$msg"
+echo "BCE: Creating python launchers in panel menu..."
 DESKTOP_DIR=/home/${BCE_USER}/.local/share/applications
-sudo -u ${BCE_USER} mkdir -p ${DESKTOP_DIR}
-
+sudo -u ${BCE_USER} mkdir -p ${DESKTOP_DIR} && \
 (
 	sudo -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/ipython.desktop
 [Desktop Entry]
@@ -74,4 +71,4 @@ StartupNotify=true
 NoDisplay=false
 EOF
 ) && \
-echo DONE: $msg || echo FAIL: $msg
+echo "  DONE" || echo "  FAIL"
diff --git a/provisioning/bootstrap.d/85-pycharm b/provisioning/bootstrap.d/85-pycharm
--- a/provisioning/bootstrap.d/85-pycharm
+++ b/provisioning/bootstrap.d/85-pycharm
@@ -1,6 +1,5 @@
 # Python stuff
-msg="BCE: Downloading PyCharm to /opt"
-echo "$msg"
+echoh "BCE: Downloading PyCharm to /opt"
 PYCHARM_DIST=pycharm-community-4.0.3
 PYCHARM_URL=http://download.jetbrains.com/python/${PYCHARM_DIST}.tar.gz
 curl -L -O ${PYCHARM_URL} && \
@@ -8,4 +7,4 @@ tar -C /opt -xzf ${PYCHARM_DIST}.tar.gz && \
 chown -R oski:oski /opt/${PYCHARM_DIST} && \
 rm ${PYCHARM_DIST}.tar.gz && \
 ( cd /usr/local/bin && ln -s /opt/${PYCHARM_DIST}/bin/pycharm.sh ) && \
-echo DONE: $msg || echo FAIL: $msg
+echo "  DONE" || echo "  FAIL"
