Use a more reliable apt mirror.

diff --git a/provisioning/bootstrap.d/10-apt-get-update b/provisioning/bootstrap.d/10-apt-get-update
--- a/provisioning/bootstrap.d/10-apt-get-update
+++ b/provisioning/bootstrap.d/10-apt-get-update
@@ -1,3 +1,8 @@
+echo "BCE: Setting apt mirror to kernel.org..."
+sed -i -e 's/us.archive.ubuntu.com/mirrors.us.kernel.org/' \
+	/etc/apt/sources.list && \
+echo "  DONE" || echo "  FAIL"
+
 echo "BCE: Updating apt cache..."
 $APT_GET update > /dev/null && \
 echo "  DONE" || echo "  FAIL"
