Disable call to etckeeper init. The etckeeper package does this during postinst.

diff --git a/provisioning/bootstrap.d/15-etckeeper b/provisioning/bootstrap.d/15-etckeeper
--- a/provisioning/bootstrap.d/15-etckeeper
+++ b/provisioning/bootstrap.d/15-etckeeper
@@ -1,12 +1,13 @@
-msg="BCE: configure etckeeper with git..."
-echo $msg
 # Track system changes
-$APT_GET install git etckeeper && \
+echo "BCE: configure etckeeper with git..."
+$APT_GET install git && \
+$APT_GET install etckeeper && \
 sed -i -e '/^VCS/s/^/#/' -e '/="git"/s/^#//' /etc/etckeeper/etckeeper.conf && \
-cd /etc && \
-# XXX - after we're done being the BCE provisioner, should we disable this
-# config? i.e., at the end of this script?
-git config --global user.name "BCE provisioner" && \
-git config --global user.email "bce@lists.berkeley.edu" && \
-etckeeper init && \
-echo DONE: $msg || echo FAIL: $msg
+(
+	# We disable this in the last boostrap step, after we're done being the BCE
+	# provisioner.
+	cd /etc && \
+	git config --global user.name "BCE provisioner" && \
+	git config --global user.email "bce@lists.berkeley.edu"
+) && \
+echo "  DONE" || echo "  FAIL"
