Remove commented code.

diff --git a/provisioning/bootstrap.d/50-oski b/provisioning/bootstrap.d/50-oski
--- a/provisioning/bootstrap.d/50-oski
+++ b/provisioning/bootstrap.d/50-oski
@@ -1,35 +1,19 @@
+echo "BCE: Configure ${BCE_USER} (and other) desktops"
+chmod 755 /home/${BCE_USER}/setup_ipython_notebook.sh && \
+echo "  DONE" || echo "  FAIL"
+
+# Enable our user to login without a password
+adduser ${BCE_USER} nopasswdlogin && \
+( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
+
 msg="BCE: Configure ${BCE_USER} user"
 echo "$msg"
 if [ "${PACKER_BUILDER_TYPE}" == "virtualbox-iso" ]; then
 	# Our user is created in the debian-installer phase
 	adduser ${BCE_USER} vboxsf
-else
-        ## not needed now that we'll use default user in a given context
-	# # Avoid interactive prompts in user creation
-	# adduser --disabled-password --gecos "" ${BCE_USER} && \
-	# echo ${BCE_USER}:${BCE_USER} | chpasswd
-fi && \
-# Enable our user to login without a password
-adduser ${BCE_USER} nopasswdlogin && \
-( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
 
-# not needed now that ubuntu is primary BCE EC2 user
-echo "BCE: Configure ${BCE_USER} (and other) desktops"
-# if [ "${PACKER_BUILDER_TYPE}" == "amazon-ebs" ]; then
-#    # We are initially copying files to the (pre-existing) ubuntu user
-#    cp -r /home/ubuntu/.config /home/${BCE_USER}/.config && \
-#    chmod 755 /home/ubuntu/setup_ipython_notebook.sh && \
-#    cp /home/ubuntu/setup_ipython_notebook.sh /home/${BCE_USER} && \
-#    chown -R ${BCE_USER}:${BCE_USER} /home/${BCE_USER}
-# else
-#    chmod 755 /home/${BCE_USER}/setup_ipython_notebook.sh
-#fi && \
-chmod 755 /home/${BCE_USER}/setup_ipython_notebook.sh && \
-echo "  DONE" || echo "  FAIL"
-
-# Create a convenient place on the desktop for people to mount and access
-# their shared directories. This may also be appropriate for VMware.
-if [ "${PACKER_BUILDER_TYPE}" == "virtualbox-iso" ]; then
+	# Create a convenient place on the desktop for people to mount and access
+	# their shared directories. This may also be appropriate for VMware.
 	echo "BCE: Configure shared directory for ${PACKER_BUILDER_TYPE}"
 	sudo -u ${BCE_USER} mkdir /home/${BCE_USER}/Desktop && \
 	sudo -u ${BCE_USER} ln -s /media /home/${BCE_USER}/Desktop/Shared && \
@@ -45,17 +29,3 @@ EOF
 	) && \
 	( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
 fi
-
-export DESKTOP_DIR=/home/${BCE_USER}/.local/share/applications
-
-## For if/when we don't want a display manager
-#     msg="BCE: Use an upstart service to automatically login ${BCE_USER} at boot"
-#     echo "$msg"
-#     ( cat <<EOF > /etc/init/bce-${BCE_USER}-desktop.conf && \
-# # Run startx on tty7 as our user
-# start on runlevel [23]
-# stop on runlevel [!23]
-# respawn
-# exec /bin/openvt -fwc 7 -- /bin/su -c /usr/bin/startx ${BCE_USER}
-# EOF
-# )
