Add nopasswdlogin group.

diff --git a/provisioning/bootstrap.d/50-user b/provisioning/bootstrap.d/50-user
--- a/provisioning/bootstrap.d/50-user
+++ b/provisioning/bootstrap.d/50-user
@@ -3,29 +3,33 @@ chmod 755 /home/${BCE_USER}/setup_ipython_notebook.sh && \
 echo "  DONE" || echo "  FAIL"
 
 # Enable our user to login without a password
+addgroup --system nopasswdlogin && \
 adduser ${BCE_USER} nopasswdlogin && \
 ( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
 
 msg="BCE: Configure ${BCE_USER} user"
 echo "$msg"
-if [ "${PACKER_BUILDER_TYPE}" == "virtualbox-iso" ]; then
-	# Our user is created in the debian-installer phase
-	adduser ${BCE_USER} vboxsf
 
-	# Create a convenient place on the desktop for people to mount and access
-	# their shared directories. This may also be appropriate for VMware.
-	echo "BCE: Configure shared directory for ${PACKER_BUILDER_TYPE}"
-	sudo -u ${BCE_USER} mkdir /home/${BCE_USER}/Desktop && \
-	sudo -u ${BCE_USER} ln -s /media /home/${BCE_USER}/Desktop/Shared && \
-	echo "  DONE" || echo "  FAIL"
+if [ "${PACKER_BUILDER_TYPE}" != "virtualbox-iso" ]; then
+	return
+fi
 
-	# Automatically login at boot
-	msg="BCE: Automatically login ${BCE_USER} at boot"
-	( cat <<EOF > /etc/lightdm/lightdm.conf
+# Our user is created in the debian-installer phase
+adduser ${BCE_USER} vboxsf
+
+# Create a convenient place on the desktop for people to mount and access
+# their shared directories. This may also be appropriate for VMware.
+echo "BCE: Configure shared directory for ${PACKER_BUILDER_TYPE}"
+sudo -u ${BCE_USER} mkdir /home/${BCE_USER}/Desktop && \
+sudo -u ${BCE_USER} ln -s /media /home/${BCE_USER}/Desktop/Shared && \
+echo "  DONE" || echo "  FAIL"
+
+# Automatically login at boot
+msg="BCE: Automatically login ${BCE_USER} at boot"
+( cat <<EOF > /etc/lightdm/lightdm.conf
 [SeatDefaults]
 autologin-user=${BCE_USER}
 autologin-user-timeout=0
 EOF
-	) && \
-	( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
-fi
+) && \
+( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
