Use Revolution Analytics MRAN as our repository for reproducable package installation.

diff --git a/provisioning/bootstrap.d/70-r b/provisioning/bootstrap.d/70-r
--- a/provisioning/bootstrap.d/70-r
+++ b/provisioning/bootstrap.d/70-r
@@ -1,22 +1,30 @@
-msg="BCE: Installing add-on R packages..."
+R_REPO="http://mran.revolutionanalytics.com/snapshot/2015-04-23/"
+R_PKGS="/tmp/packages/R-packages.txt"
+
+U_CODE=$(lsb_release -c -s)
+
+msg="BCE: Configure apt repository for R packages."
 echo "$msg"
-if [ "${USE_SAVED_PKG_SRC}" == "True" ]; then
-        cd /tmp/R
-        Rscript -e "library(tools); write_PACKAGES('/tmp/R/'); \
-        pkgs <- list.files(); pkgs <- pkgs[grep('tar.gz', pkgs)]; \
-        pkgs <- gsub('_[0-9].*tar.gz', '', pkgs); \
-        pkgs <- gsub('-[0-9].*tar.gz', '', pkgs); \
-        install.packages(pkgs, contriburl = 'file:///tmp/R/')"
-else
-        Rscript -e "pkgs <- scan('/tmp/packages/R-packages.txt', what = 'character'); \ 
-        install.packages(pkgs, repos = 'http://cran.cnr.berkeley.edu')" 
-fi && \
+echo "deb ${R_REPO}/bin/linux/ubuntu ${U_CODE}/" >> \
+	/etc/apt/sources.list.d/mran.list && \
+gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9 && \
+gpg -a --export E084DAB9 | sudo apt-key add - && \
+( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
+
+msg="BCE: Define our R repository."
+echo "$msg"
+echo "options(repos = list(CRAN = '${R_REPO}'))" >> /etc/R/Rprofile.site && \
+( echo "  DONE" ; etckeeper commit "$msg" ) || echo "  FAIL"
+
+msg="BCE: Install R packages."
+echo "$msg"
+Rscript -e \
+	"install.packages(scan('${R_PKGS}', what='char'), repos='${R_REPO}')" && \
 echo "  DONE" || echo "  FAIL"
 
-echo "BCE: Adding R to Development menu..."
+echo "BCE: Add R to Development menu."
 sed -i \
 	-e '/^Categories=/s/Graphics;//' \
 	-e '/^Categories=/s/=/=Development;/' \
 	/usr/share/applications/R.desktop && \
 echo "  DONE" || echo "  FAIL"
-
