Install python3 libraries using a new requirements file.

diff --git a/provisioning/bootstrap.d/80-python b/provisioning/bootstrap.d/80-python
--- a/provisioning/bootstrap.d/80-python
+++ b/provisioning/bootstrap.d/80-python
@@ -1,22 +1,35 @@
-echo "BCE: Installing Python modules..."
+function pip_install () {
+	PYTHON="$1"
+	PIP="$2"
+	REQS_FILE="$3"
+	echo "BCE: Installing ${PYTHON} modules from ${REQS_FILE} using ${PIP}..."
+	${PYTHON} /tmp/get-pip.py && \
+	for p in $(egrep -v '^$|^#' ${REQS_FILE}); do
+		echo "============================================================"
+		cmd="${PIP} install --log /home/${BCE_USER}/.cache/pip/${PIP}-${p}.log --upgrade $p"
+		echo $cmd
+		$cmd
+	done && \
+	echo "  DONE" || echo "  FAIL"
+}
+
+# Silence warnings that this doesn't exist
+sudo -H -u oski mkdir -p /home/${BCE_USER}/.cache/pip/log
+
 # We install pip directly from pypa to avoid conflicts with requests
+echo "BCE: Fetching get-pip.py..."
 curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && \
-python /tmp/get-pip.py && \
-for p in $(egrep -v '^$|^#' /tmp/packages/python-requirements.txt); do
-	echo "============================================================"
-	cmd="pip install --upgrade $p"
-	echo $cmd
-	$cmd
-done && \
 echo "  DONE" || echo "  FAIL"
-# This isn't as reliable as doing one at a time
-#pip install --upgrade -r /tmp/packages/python-requirements.txt && \
+
+# Install the packages, one by one
+pip_install python    pip  /tmp/packages/python-requirements.txt
+pip_install python3.4 pip3 /tmp/packages/python3-requirements.txt
 
 echo "BCE: Creating python launchers in panel menu..."
 DESKTOP_DIR=/home/${BCE_USER}/.local/share/applications
-sudo -u ${BCE_USER} mkdir -p ${DESKTOP_DIR} && \
+sudo -H -u ${BCE_USER} mkdir -p ${DESKTOP_DIR} && \
 (
-	sudo -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/ipython.desktop
+	sudo -H -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/ipython.desktop
 [Desktop Entry]
 Name=IPython
 Comment=IPython Interpreter
@@ -30,7 +43,7 @@ NoDisplay=false
 EOF
 ) && \
 (
-	sudo -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/ipython-notebook.desktop
+	sudo -H -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/ipython-notebook.desktop
 [Desktop Entry]
 Name=IPython Notebook
 Comment=IPython Notebook
@@ -44,7 +57,7 @@ NoDisplay=false
 EOF
 ) && \
 (
-	sudo -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/python2.7.desktop
+	sudo -H -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/python2.7.desktop
 [Desktop Entry]
 Name=Python 2.7
 Comment=Python 2.7
@@ -58,7 +71,7 @@ NoDisplay=false
 EOF
 ) && \
 (
-	sudo -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/python3.4.desktop
+	sudo -H -u ${BCE_USER} cat <<EOF > ${DESKTOP_DIR}/python3.4.desktop
 [Desktop Entry]
 Name=Python 3.4
 Comment=Python 3.4
