Loop over package list and install each one separately for more reliable installs.

diff --git a/provisioning/bootstrap.d/_80-anaconda-user b/provisioning/bootstrap.d/_80-anaconda-user
--- a/provisioning/bootstrap.d/_80-anaconda-user
+++ b/provisioning/bootstrap.d/_80-anaconda-user
@@ -4,17 +4,20 @@
 
 function manual_install_conda_packages() {
 
+	arg=$1
+
+	pb="singledispatch==3.4.0.3 rpy2==2.5.6 ipythonblocks==1.7.0 chardet==2.3.0"
+	if [ -z "$arg" -o "$arg" == "2" ]; then
+		pb="$pb chardet==2.3.0"
+	fi
+
 	# Not available yet
 	echo "BCE: Installing packages with conda pipbuild..."
-	for pv in \
-		singledispatch==3.4.0.3 \
-		rpy2==2.5.6 \
-		ipythonblocks==1.7.0 \
-		chardet==2.3.0 \
-		; do
+	for pv in $pb ; do
 		p=${pv/==*/}
 		v=${pv/*==/}
 
+		echo "BCE:   ${pv}"
 		conda pipbuild --no-binstar-upload ${p}	--release ${v}
 		conda install --yes --use-local ${pv}
 	done && \
@@ -53,15 +56,22 @@ echo "BCE: Prepending miniconda to PATH..."
 source ${HOME}/miniconda/bin/activate ${HOME}/miniconda
 
 # These can only be in the root environment
+echo "BCE: Installing python 2.7 packages with conda..."
 conda install --yes conda==3.11.0 conda-build==1.12 conda-env==2.1.4
-echo "BCE: Installing packages with conda..."
-conda install --yes $(cat /tmp/packages/conda-requirements-py27.txt) && \
-echo "  DONE" || echo "  FAIL"
 
-conda create --yes -n py34 python=3.4 && \
-source activate py34
-echo "BCE: Installing packages with conda..."
-conda install --yes $(cat /tmp/packages/conda-requirements-py34.txt) && \
+for p in $(cat /tmp/packages/conda-requirements-py27.txt); do
+	conda install --yes ${p}
+done && \
 echo "  DONE" || echo "  FAIL"
 
 manual_install_conda_packages
+
+echo "BCE: Installing python 3.4 packages with conda..."
+conda create --yes -n py34 python=3.4 && \
+source activate py34
+for p in $(cat /tmp/packages/conda-requirements-py34.txt); do
+	conda install --yes ${p}
+done && \
+echo "  DONE" || echo "  FAIL"
+
+manual_install_conda_packages 3.4
