Do not try to install python2-only libraries into python3 environment. Install datascience library.

diff --git a/provisioning/bootstrap.d/_80-anaconda-user b/provisioning/bootstrap.d/_80-anaconda-user
--- a/provisioning/bootstrap.d/_80-anaconda-user
+++ b/provisioning/bootstrap.d/_80-anaconda-user
@@ -6,25 +6,26 @@ function manual_install_conda_packages() {
 
 	arg=$1
 
-	pb="singledispatch==3.4.0.3 rpy2==2.5.6 ipythonblocks==1.7.0 chardet==2.3.0"
 	if [ -z "$arg" -o "$arg" == "2" ]; then
-		pb="$pb chardet==2.3.0"
+		# These pipbuild packages are not compatible with Python 3.
+		pb="rpy2==2.5.6 singledispatch==3.4.0.3"
+
+		# Not available via conda yet
+		echo "BCE: Installing packages with conda pipbuild..."
+
+		for pv in $pb ; do
+			p=${pv/==*/}
+			v=${pv/*==/}
+
+			echo "BCE:   ${pv}"
+			conda pipbuild ${p}	--release ${v}
+			conda install --yes --use-local ${pv}
+		done && \
+		echo "  DONE" || echo "  FAIL"
 	fi
 
-	# Not available yet
-	echo "BCE: Installing packages with conda pipbuild..."
-	for pv in $pb ; do
-		p=${pv/==*/}
-		v=${pv/*==/}
-
-		echo "BCE:   ${pv}"
-		conda pipbuild --no-binstar-upload ${p}	--release ${v}
-		conda install --yes --use-local ${pv}
-	done && \
-	echo "  DONE" || echo "  FAIL"
-
 	# These do not pipbuild cleanly
-	PIPINSTALL="sklearn-pandas==0.0.9"
+	PIPINSTALL="sklearn-pandas==0.0.9 datascience==0.3.dev21"
 
 	for pi in ${PIPINSTALL} ; do
 		pip install ${pi}
